[package]
name = "thermo_properties"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
diesel = { version = "2.2.2", features = ["postgres"] }
dotenvy = "0.15.7"
