[package]
name = "thermo_properties"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
csv = "1.3.0"
diesel = { version = "2.2.2", features = ["postgres"] }
dotenvy = "0.15.7"
serde = { version = "1.0.204", features = ["derive"] }
